server {
    listen 80;

    location / {
        return 200 'Hello from sandbox env\n';
        add_header Content-Type text/plain;
    }

    location /health {
        return 200 '{"status":"ok"}\n';
        add_header Content-Type application/json;
    }
}